[packages.demo]
# Ordered list of paths bundled into the deploy archive (no glob expansion)
sources = ["./dist/demo"]

[remotes."192.168.50.11"]
# Host-specific remote block keyed by IP or alias
# gRPC port exposed by the adeploy server
port = 6060
# Reserved RPC timeout (seconds) for client operations
timeout = 30
# Optional path to the SSH public key authorizing deployments
key_path = ".key/id_ed25519.pub"

[remotes.default]
# Fallback settings when a remote entry is missing
# Keep port aligned with the server listener configuration
port = 6060
# Timeout override applied to hosts without their own entry
timeout = 30
# Shared key path used when a dedicated key is not supplied
key_path = ".key/id_ed25519.pub"
